version: '3.3'

services:
  fastapi:
    build: .
    image: fastapi
    restart: always
    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    expose:
      - 8000

  nginx: 
    image: nginx:1.25.2-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d